[[main]]
  none = "none"

[[main]]
  name = "Articles"
  pageRef = "posts"
  weight = 1

[[main]]
  identifier = "categories"
  name = "Catégories"
  pageRef = "categories"
  weight = 2

[[main]]
  name = "People Management"
  parent = "categories"
  pageRef = "people-management"
  weight = 21

[[main]]
  name = "Product Management"
  parent = "categories"
  pageRef = "product-management"
  weight = 22

[[main]]
  name = "Organisation"
  parent = "categories"
  pageRef = "organization"
  weight = 23

[[main]]
  name = "Tech"
  parent = "categories"
  pageRef = "tech"
  weight = 24

[[main]]
  identifier = "projects"
  name = "Projets"
  pageRef = "projects"
  weight = 3

[[main]]
  name = "SARA"
  parent = "projects"
  pageRef = "sara"
  weight = 31

[[main]]
  name = "Atelier Claude Code"
  parent = "projects"
  pageRef = "claude-code-workshop"
  weight = 32

[[main]]
  name = "A Propos"
  pageRef = "about"
  weight = 4

[[footer]]
  none = "none"
